theme = "kanagawa"

[editor]
line-number = "relative"
true-color = true
undercurl = true
color-modes = true
cursorline = true
auto-save = true # save when window looses focus
idle-timeout = 0
# original gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "â†’"

[editor.file-picker]
hidden = false # show hidden files as in starting with a dot
git-global = false # show files hidden by git globally

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", ":w"] # remove additional cursors and selections
'C-6' = ":quit"
y = "yank_joined_to_clipboard" # use my system clipboard
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
d = ["yank_joined_to_clipboard", "delete_selection", ":w"] # add deleted text to system clipboaard
# X = ["extend_line_up", "extend_to_line_bounds"]
x = "select_line_below"
X = "select_line_above"
A-x = "extend_to_line_bounds"
";" = "flip_selections"
"," = "repeat_last_motion"
0 = "goto_line_start"
'$' = "extend_to_line_end"
G = "goto_last_line"

[keys.select]
esc = ["collapse_selection", "normal_mode"] # remove selections
y = "yank_joined_to_clipboard"
p = "replace_selections_with_clipboard"
P = "replace_selections_with_clipboard"
d = ["yank_joined_to_clipboard", "delete_selection", ":w"] # add deleted text to system clipboaard
# #c = ["trim_selections", "change_selection"] # when changing a line this stops the cursor moving to the beginning of the line underneath
";" = "flip_selections"
"," = "repeat_last_motion"
0 = "goto_line_start"
'$' = "extend_to_line_end"
G = "goto_last_line"
x = "select_line_below"
X = "select_line_above"
A-x = "extend_to_line_bounds"

[keys.insert]
pageup = "half_page_up"
pagedown = "half_page_down"
esc = [":w", "normal_mode"]

[keys.normal.space]
# Add comma to the end of the line
"," = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ','",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
# Add semicolumn to the end of the line
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ';'",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
F = "file_picker_in_current_buffer_directory" # useful for accessing sibling files rather than a file tree
"." = ":toggle-option file-picker.git-ignore" # toggle seeing files hidden with the .gitignore in file pickers
"=" = ":format"
"+" = ":indent-style 4"
q = ":q"
Q = ":q!"
">" = ":cd %sh{dirname %{buffer_name}}"
